### ISSUE TITLE
create shiny server

### ISSUE THREAD

**Issue by tedinciong** [rsangole/capstone_project#10]
Currently trying to install the VM shiny server, but unable to run fab vagrant setup_vagrant

**Comment by rsangole** [comment]
Awesome! Your first issue!

**Comment by tedinciong** [comment]
shifted from VM Shiny Sever Open Source and moved to Shinyapp.io.

https://capstone498-wi19-team54-wnv.shinyapps.io/chicagoMap2/

**Comment by rsangole** [comment]
Awesome
