### ISSUE TITLE
Perform feature engineering

### ISSUE THREAD

**Issue by rsangole** [rsangole/capstone_project#12]
Team,

As we look at the data, please populate your feature engineering ideas here.

**Comment by andrew3cooper** [comment]
Aggregate weather data to get mean/min/max daily temperatures in 7/14/21/28 days prior to mosquito trap test date.  Also get total precipitation in 7/14/21/28 days prior, plus counts of consecutive low precipitation days (i.e. droughts).

**Comment by rsangole** [comment]
Based on reading 

https://www.evolvedatascience.com/post/2016-12-17-wnv-blogpost/

few ideas for us to try:

- [ ] moving averages for all the weather columns
- [ ] {traps+lat+long} based clustering , then create a new column for cluster number

**Comment by andrew3cooper** [comment]
Great ideas, Rahul.  I think moving averages for weather data may be particularly useful.
