### ISSUE TITLE
identify data sources for interactive overlay (schools, senior centers, hospitals, etc.)

### ISSUE THREAD

**Issue by tedinciong** [rsangole/capstone_project#15]

**Comment by rsangole** [comment]
@tedinciong and @racheldudle  -- I think you'll want to connect with @andrew3cooper  on this stuff

**Comment by andrew3cooper** [comment]
I could probably convert shapefiles (.shp, etc.) to .RDS files if that would help....

**Comment by tedinciong** [comment]
Thanks, @andrew3cooper.  I'm using the following files.  @racheldudle - here are the files I'm using for the shiny app - its still pretty raw.

chicago zipcode (outlines zip codes for map): https://raw.githubusercontent.com/rsangole/capstone_project/master/data/raw/chizip.csv")

trap locations and +WNV (for spatial location and heatmap)
https://raw.githubusercontent.com/rsangole/capstone_project/master/data/processed/wnv.trap.date.rev3b.csv

chicago hospitals https://raw.githubusercontent.com/rsangole/capstone_project/master/data/raw/hospitals/hospitals.csv

chicago schools  https://raw.githubusercontent.com/rsangole/capstone_project/master/data/raw/schools/School%20Point%202014.csv

senior centers  https://raw.githubusercontent.com/rsangole/capstone_project/master/data/raw/senior_centers/senior.centers.csv
