### ISSUE TITLE
align with Rachel and team on visualization to use in desktop and mobile app

### ISSUE THREAD

**Issue by tedinciong** [rsangole/capstone_project#16]

**Comment by rsangole** [comment]
@racheldudle and @tedinciong  - were you able to get alignment on this topic?

**Comment by tedinciong** [comment]
@racheldudle - let me know when you have some time to discuss idea.  we can do this through slack/bluejeans - i'm flexible.  once we align then we can propose to the team our thoughts.

**Comment by tedinciong** [comment]
@racheldudle - I've uploaded an RDS file which I converted from cityofchicago.data.   this may be easier to work with compared to the neighborhood file i originally sent.

https://github.com/rsangole/capstone_project/blob/master/data/raw/chizip.RDS

**Comment by racheldudle** [comment]
Hi @tedinciong is this still a good gile to use? Can you convert to .rdata or .rda?

**Comment by tedinciong** [comment]
I loaded a CSV -> https://raw.githubusercontent.com/rsangole/capstone_project/master/data/raw/chizip.csv

I'm using the $zip to outline the Chicago zip codes

**Comment by tedinciong** [comment]
Here's the Data

https://github.com/rsangole/capstone_project/blob/master/data/raw/chizip.RData?raw=true
