### ISSUE TITLE
Write common data input, cleanup and munging codes

### ISSUE THREAD

**Issue by rsangole** [rsangole/capstone_project#2]

**Comment by rsangole** [comment]
@andrew3cooper Hello

**Comment by kapelinskim6** [comment]
I was able to pull the 32 pg. Ohare Climate PDF into a csv. It has data from 2017 to 2018 for temp and rainfall/snow.

**Comment by rsangole** [comment]
![image](https://user-images.githubusercontent.com/6344050/52458343-da262880-2b2c-11e9-8394-b2025b5e9176.png)

![image](https://user-images.githubusercontent.com/6344050/52458329-cda1d000-2b2c-11e9-98c6-3d953b07b3f1.png)

**Comment by rsangole** [comment]
@andrew3cooper @kapelinskim6  I think this task is pretty much complete, right? Anything else you can think of? Shall we close it?

**Comment by rsangole** [comment]
Marking complete now.
