### ISSUE TITLE
Spray data EDA

### ISSUE THREAD

**Issue by andrew3cooper** [rsangole/capstone_project#20]
Does someone want to run EDA on the two years of mosquito spray data we have from kaggle?  

I'm curious what we'll see, and I'd like to confirm that  spray data is readily predicted by recent past history of positive WNV test results, plus whether mosquito counts are inversely related to recent past history of spraying.  The latter two will require modeling but it doesn't have to be fancy.

**Comment by rsangole** [comment]
@stephenhage  - Could you help run some EDA on the new datasets and get us some insights?
