### ISSUE TITLE
Building data EDA and reshaping

### ISSUE THREAD

**Issue by andrew3cooper** [rsangole/capstone_project#22]
I did a lot of work geocoding and reshaping building violations & abandoned/vacant property data, but I'm not sure yet if it'll be useful as is.  Vacancy data in particular is very sparse if you look at small geographic areas (block group rather than community area, for example).  Is there anything more we could do?  Should we standardize data somehow, e.g. divide number of violations/vacancies by population in that geographic area?

**Comment by rsangole** [comment]
From the modeler's standpoint, if I was running ONE model, with zipcode as a predictor, I might just aggregate the "count of abandoned/vacant lots" for each zipcode as a new feature variable.

**Comment by andrew3cooper** [comment]
Sounds reasonable.  I actually have these data aggregated already in the main zipped csv dataset.  Census block group is more granular and specific to the trap location but probably too sparse.  Zip code level (zcta) may work.

**Comment by rsangole** [comment]
@andrew3cooper  -  I think you've completed this one, right?

**Comment by andrew3cooper** [comment]
Tentatively.  If we have time, I might go back and aggregate these data over different time windows and/or filter to specific building violation types to see what's most predictive.  But we can probably table that for now since there's a lot more in the hopper.

**Comment by rsangole** [comment]
Yep, agreed. Thanks Andrew.
