### ISSUE TITLE
Additional lagged weather columns

### ISSUE THREAD

**Issue by rsangole** [rsangole/capstone_project#33]
Could we add the following columns to the data, when you get a chance?

- [x] 2wk_precip - For each day, the preceding 2-week average for precip
- [x] 4wk_precip
- [x] 90day_precip
- [x] 2wk_tavg
- [x] 4wk_tavg
- [x] 2wk_mintemp
- [x] 4wk_mintemp

**Comment by andrew3cooper** [comment]
Sorry for the delay here.  Data updated.  R code, R data and CSV pushed to GitHub now.

**Comment by rsangole** [comment]
Not at all! awesome Andrew thanks!
