### ISSUE TITLE
Calculate distance from trap and add to schools, hospitals, and SC

### ISSUE THREAD

**Issue by tedinciong** [rsangole/capstone_project#35]
At a minimum, each of these locations (school, hospital, SC) should provide information to the user on the nearest trap.  EG. 

Nearest Trap: T009
Location: (Address or neighborhood)
Last Time to Test Positive for WNV: Date
Projected Date to Test Positive for WNV: Date
Likelihood to Test Positive: (From Model)
Severity of Testing Positive: (Based on distance from Trap)

**Comment by rsangole** [comment]
Yep. This looks good.
