### ISSUE TITLE
Obtain weather data -- since NOAA site is down, maybe try scraping weather data 2007-18

### ISSUE THREAD

**Issue by andrew3cooper** [rsangole/capstone_project#4]
Since data.NOAA.gov site is down due to government shutdown, someone could try scraping weather data.  Try following the Python tutorial posted in Canvas.  

We do have kaggle's NOAA extract for 2007-14.  They included data from two unidentified weather stations.  If we can get data from multiple weather stations closer to the WNV traps, that should improve our models.

**Comment by andrew3cooper** [comment]
I obtained weather data 2006-18 from NOAA.  I will add it to the github repo.

**Comment by andrew3cooper** [comment]
We could still check to see if another data source will give us more/different weather stations....

**Comment by andrew3cooper** [comment]
I manually uploaded the NOAA daily weather and google trend data to github.  Take a look at the NOAA data.  It actually contains partial or complete data from more than 100 Chicago-area weather stations for 2006-18....

**Comment by rsangole** [comment]
@andrew3cooper I see it now. I've moved these to a new folder. Is there a data dictionary for these available? What do the columns mean? and which ones do we care about?

**Comment by andrew3cooper** [comment]
I added combined CSV files after subsetting to 20 stations with nearly complete daily data.  I also found another source for Midway/O'Hare stations (Frontier Weather Inc) but it really wasn't any better.

**Comment by rsangole** [comment]
> @rsangole Sorry, I moved it from raw to processed before seeing this. Is the processed folder for CSVs or once we combine multiple CSVs together.

No worries Mike. Let's make sure they're in the right folder now. `processed` folder is only for fully-preprocessed "ready-for-modeling" files.

**Comment by rsangole** [comment]
> I added combined CSV files after subsetting to 20 stations with nearly complete daily data. I also found another source for Midway/O'Hare stations (Frontier Weather Inc) but it really wasn't any better.

Andrew, where are these now? I see lots of weather data files... which ones are the "final" ones to use?

**Comment by rsangole** [comment]
@andrew3cooper @kapelinskim6 Could you remind me again why we're scraping weather data? i.e. the weather data which the Kaggle competition offered... is that incomplete?

**Comment by andrew3cooper** [comment]
Weather data from kaggle only covers 2007-14, not 2007-18 like the mosquito trap data.  I got a full set of 2007-18 data from data.noaa.gov which turns out to have >300 stations in the Chicago area with a variety of different variables depending on which station(s) we use.  I want to run EDA and think about which variables might be useful.

**Comment by andrew3cooper** [comment]
Github wouldn't let me  upload complete data due to file size, so I subset to the 20 weather stations with nearly complete daily data.  That's a good version to work from, though we need further aggregation (feature engineering) as we merge with mosquito trap data.  I may want to take a second look at the other 280+ stations as well to see if anything else looks useful.

**Comment by rsangole** [comment]
Ah, thanks Andrew. Based on what I saw in a kaggle kernel, just using even 2 weather stations got folks a score of 0.85 using deep learning. My plan is to do the same - start small, then add features if needed.

It sounds like we are ready to do one big join + train-test split tonight? If you agree, shall we have a teleconf tonight and finish it off?

**Comment by andrew3cooper** [comment]
That's a good plan, though I'm not sure if I'll be able to connect tonight (I have to take my son to scouts tonight and again tomorrow morning).  There will probably be additional variables added for a couple more days, but I see no reason not to get started small, like you said.  The train/validate/test split will be easy enough to do based on year -- I think maybe 2007-13 training, 2014-16 validation, 2017-18 test.  What do you think?

**Comment by rsangole** [comment]
I think we should nail down a dataset right away to get everyone started. Else, we'll lag behind the other teams. We can always add new columns later. We will make sure we have a unique "ROW_ID" identifier to keep traceability of each observation.

Those splits seem reasonable to me. Let's use those.

**Comment by andrew3cooper** [comment]
My biggest question is whether the wnv.trap.date file is organized the way you would want it for your proposed models?  If you can take a look at that and see how it differs from the raw Chicago Dept of Public Health data, we could definitely move ahead.  I also wrote some notes about this under the issue related to modeling.

**Comment by rsangole** [comment]
Ok, I'll look at this tonight. I'm not sure either. I feel like we should create one "unaggregated" wide-form dataset >> split it up >> then create our own aggregates as needed.
