### ISSUE TITLE
Exploratory Data Analysis - Summarizations, Graphs and Plots

### ISSUE THREAD

**Issue by rsangole** [rsangole/capstone_project#7]
Everyone:

You can contribute to the EDA phase of the project by performing various visualizations and summaries. These should be published in some form back to the team - either rmarkdown documents, jupyter notebooks, PDFs, or simply a word document. 

**Ideas for visualizations:**

- [ ] Time series plots for various continuous predictors
- [ ] Time series plots for response variable
- [ ] Boxplots for categorical variables
- [ ] Scatter plots color coded by categoricals
- [ ] Scatter plots color coded by response
- [ ] Maps + overlaps of various predictors and response
- [ ] Clustering and cluster plots
- [ ] TSNE plots
- [ ] Density plots grouped by categoricals and response

Linking two new issues Andrew has created: #20 and #21

**Comment by rsangole** [comment]
@andrew3cooper @tedinciong @stephenhage @kapelinskim6  - Calling all members! Please review the data under processed, and get some EDA up and running! Keep the team updated here on which data you're doing EDA on and what kinds of EDA, so we don't repeat ourselves.

**Comment by rsangole** [comment]
![image](https://user-images.githubusercontent.com/6344050/52171932-b1202500-2733-11e9-9f81-b5aae7c300a4.png)

Some zipcodes don't have data beyond the 1st year.

I propose we drop these zipcodes and make our lives easier.

**Comment by rsangole** [comment]
**Quick EDA observations on the weather data...**

Selecting all 60 weather variables show high amounts of collinearity (no surprise there...). PCA shows first 3 components explain 91% of the variation.

![image](https://user-images.githubusercontent.com/6344050/52458713-12c70180-2b2f-11e9-8b18-3b13d6b1c79c.png)

![image](https://user-images.githubusercontent.com/6344050/52458725-1fe3f080-2b2f-11e9-966b-c530d2522e29.png)

**Clustering these 60 observations**

Perhaps 4 clusters?
![image](https://user-images.githubusercontent.com/6344050/52458799-7fda9700-2b2f-11e9-8aed-268e67858131.png)

But, not very clean clusters... 
![image](https://user-images.githubusercontent.com/6344050/52459031-ce3c6580-2b30-11e9-9f63-897e5f131349.png)

**Comment by andrew3cooper** [comment]
Nicely done.

**Comment by rsangole** [comment]
### Zone Class and Zone Type

This seems to be predictive. Look at the % wnv_present/absent vs these two vars. Some zones are more "active".

![image](https://user-images.githubusercontent.com/6344050/52513463-e667bf80-2bd8-11e9-95f0-c93ceaab4edf.png)
![image](https://user-images.githubusercontent.com/6344050/52513465-e8ca1980-2bd8-11e9-9ff6-4e1c58754469.png)

**Comment by andrew3cooper** [comment]
Yes. Good find.  I noticed the same thing.  I've been pondering why that is (correlation vs. causation; confounding), but for predictive purposes, I don't think it really matters.

**Comment by andrew3cooper** [comment]
Yes. Good find.  I noticed the same thing.  I've been pondering why that is (correlation vs. causation; confounding), but for predictive purposes, I don't think it really matters.

**Comment by andrew3cooper** [comment]
Note that zoning class rolls up to type.

**Comment by rsangole** [comment]
> Note that zoning class rolls up to type.

Yep, Figured that out when I did my `xtabs`. I'm still debating which one to keep for now :)

**Comment by rsangole** [comment]
All my further EDA will be documented [**here**](https://github.com/rsangole/capstone_project/blob/master/src/rahul/04-EDA.ipynb)

**Comment by andrew3cooper** [comment]
I reviewed your EDA over the weekend, Rahul.  Great work.  Took another look during my lunch break today & I have a few comments to make, probably later tonight.

**Comment by tedinciong** [comment]
[EDA.pdf](https://github.com/rsangole/capstone_project/files/2865453/EDA.pdf)
some additional basic eda
