### ISSUE TITLE
Submit Week 3 - Status Report on Canvas

### ISSUE THREAD

**Issue by rsangole** [rsangole/capstone_project#8]
We need to submit 1 post for a "team" status update. And each of us need to submit a post for what we've done this week.

https://canvas.northwestern.edu/courses/89193/discussion_topics/552870

**Comment by kapelinskim6** [comment]
I will start drafting a post now and fill in the content from the work that gets completed tonight and tomorrow morning before submitting.

**Comment by andrew3cooper** [comment]
Thanks @kapelinskim6 .  I had just started drafting a post myself before seeing your comment, but I'll wait for you to take the lead.  Thanks!

**Comment by rsangole** [comment]
> I will start drafting a post now and fill in the content from the work that gets completed tonight and tomorrow morning before submitting.

Let me know if there are sections you'd want me to fill in...

**Comment by rsangole** [comment]
This team had an excellent approach towards putting forth their week 3 update for Don.

[Week3Status_LettucePredict.pdf](https://github.com/rsangole/capstone_project/files/2799803/Week3Status_LettucePredict.pdf)

**Comment by rsangole** [comment]
Marking as complete.
